#include "LED.h"

//Blue
void LED_L_Init(void)
{
	HAL_GPIO_WritePin(LED_0_B_GPIO_Port, LED_0_B_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LED_R_45_B_GPIO_Port, LED_R_45_B_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LED_R_90_B_GPIO_Port, LED_R_90_B_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LED_R_135_B_GPIO_Port, LED_R_135_B_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LED_L_45_B_GPIO_Port, LED_L_45_B_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LED_L_90_B_GPIO_Port, LED_L_90_B_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LED_L_135_B_GPIO_Port, LED_L_135_B_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LED_180_B_GPIO_Port, LED_180_B_Pin, GPIO_PIN_RESET);
}


void LED_L_op(float deg)
{
//	if((deg >= 0 && deg < 45) || (deg == 360))
	if (deg < 23)
	{
		HAL_GPIO_WritePin(LED_0_B_GPIO_Port, LED_0_B_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(LED_R_45_B_GPIO_Port, LED_R_45_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_90_B_GPIO_Port, LED_R_90_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_135_B_GPIO_Port, LED_R_135_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_45_B_GPIO_Port, LED_L_45_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_90_B_GPIO_Port, LED_L_90_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_135_B_GPIO_Port, LED_L_135_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_180_B_GPIO_Port, LED_180_B_Pin, GPIO_PIN_RESET);
	}
//	else if(deg >= 45 && deg < 90)
	else if (deg < 23 + 45)
	{
		HAL_GPIO_WritePin(LED_0_B_GPIO_Port, LED_0_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_45_B_GPIO_Port, LED_R_45_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_90_B_GPIO_Port, LED_R_90_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_135_B_GPIO_Port, LED_R_135_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_45_B_GPIO_Port, LED_L_45_B_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(LED_L_90_B_GPIO_Port, LED_L_90_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_135_B_GPIO_Port, LED_L_135_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_180_B_GPIO_Port, LED_180_B_Pin, GPIO_PIN_RESET);
	}
//	else if(deg >= 90 && deg < 135)
	else if (deg < 23 + 45 * 2)
	{
		HAL_GPIO_WritePin(LED_0_B_GPIO_Port, LED_0_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_45_B_GPIO_Port, LED_R_45_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_90_B_GPIO_Port, LED_R_90_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_135_B_GPIO_Port, LED_R_135_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_45_B_GPIO_Port, LED_L_45_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_90_B_GPIO_Port, LED_L_90_B_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(LED_L_135_B_GPIO_Port, LED_L_135_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_180_B_GPIO_Port, LED_180_B_Pin, GPIO_PIN_RESET);
	}
//	else if(deg >= 135 && deg < 180)
	else if (deg < 23 + 45 * 3)
	{
		HAL_GPIO_WritePin(LED_0_B_GPIO_Port, LED_0_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_45_B_GPIO_Port, LED_R_45_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_90_B_GPIO_Port, LED_R_90_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_135_B_GPIO_Port, LED_R_135_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_45_B_GPIO_Port, LED_L_45_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_90_B_GPIO_Port, LED_L_90_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_135_B_GPIO_Port, LED_L_135_B_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(LED_180_B_GPIO_Port, LED_180_B_Pin, GPIO_PIN_RESET);
	}
//	else if(deg >= 180 && deg < 225)
	else if (deg < 23 + 45 * 4)
	{
		HAL_GPIO_WritePin(LED_0_B_GPIO_Port, LED_0_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_45_B_GPIO_Port, LED_R_45_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_90_B_GPIO_Port, LED_R_90_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_135_B_GPIO_Port, LED_R_135_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_45_B_GPIO_Port, LED_L_45_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_90_B_GPIO_Port, LED_L_90_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_135_B_GPIO_Port, LED_L_135_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_180_B_GPIO_Port, LED_180_B_Pin, GPIO_PIN_SET);
	}
//	else if(deg >= 225 && deg < 270)
	else if (deg < 23 + 45 * 5)
	{
		HAL_GPIO_WritePin(LED_0_B_GPIO_Port, LED_0_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_45_B_GPIO_Port, LED_R_45_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_90_B_GPIO_Port, LED_R_90_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_135_B_GPIO_Port, LED_R_135_B_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(LED_L_45_B_GPIO_Port, LED_L_45_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_90_B_GPIO_Port, LED_L_90_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_135_B_GPIO_Port, LED_L_135_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_180_B_GPIO_Port, LED_180_B_Pin, GPIO_PIN_RESET);
	}
//	else if(deg >= 270 && deg < 315)
	else if (deg < 23 + 45 * 6)
	{
		HAL_GPIO_WritePin(LED_0_B_GPIO_Port, LED_0_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_45_B_GPIO_Port, LED_R_45_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_90_B_GPIO_Port, LED_R_90_B_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(LED_R_135_B_GPIO_Port, LED_R_135_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_45_B_GPIO_Port, LED_L_45_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_90_B_GPIO_Port, LED_L_90_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_135_B_GPIO_Port, LED_L_135_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_180_B_GPIO_Port, LED_180_B_Pin, GPIO_PIN_RESET);
	}
//	else if(deg >= 315 && deg < 360)
	else if (deg < 23 + 45 * 7)
	{
		HAL_GPIO_WritePin(LED_0_B_GPIO_Port, LED_0_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_45_B_GPIO_Port, LED_R_45_B_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(LED_R_90_B_GPIO_Port, LED_R_90_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_135_B_GPIO_Port, LED_R_135_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_45_B_GPIO_Port, LED_L_45_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_90_B_GPIO_Port, LED_L_90_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_135_B_GPIO_Port, LED_L_135_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_180_B_GPIO_Port, LED_180_B_Pin, GPIO_PIN_RESET);
	}
	else if(deg < 360)
	{
		HAL_GPIO_WritePin(LED_0_B_GPIO_Port, LED_0_B_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(LED_R_45_B_GPIO_Port, LED_R_45_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_90_B_GPIO_Port, LED_R_90_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_135_B_GPIO_Port, LED_R_135_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_45_B_GPIO_Port, LED_L_45_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_90_B_GPIO_Port, LED_L_90_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_135_B_GPIO_Port, LED_L_135_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_180_B_GPIO_Port, LED_180_B_Pin, GPIO_PIN_RESET);
	}
}

//Red
void LED_R_Init(void)
{
	HAL_GPIO_WritePin(LED_0_R_GPIO_Port, LED_0_R_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LED_R_45_R_GPIO_Port, LED_R_45_R_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LED_R_90_R_GPIO_Port, LED_R_90_R_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LED_R_135_R_GPIO_Port, LED_R_135_R_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LED_L_45_R_GPIO_Port, LED_L_45_R_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LED_L_90_R_GPIO_Port, LED_L_90_R_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LED_L_135_R_GPIO_Port, LED_L_135_R_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LED_180_R_GPIO_Port, LED_180_R_Pin, GPIO_PIN_RESET);
}


void LED_R_op(float deg)
{
	if (deg < 23)
	{
		HAL_GPIO_WritePin(LED_0_R_GPIO_Port, LED_0_R_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(LED_R_45_R_GPIO_Port, LED_R_45_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_90_R_GPIO_Port, LED_R_90_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_135_R_GPIO_Port, LED_R_135_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_45_R_GPIO_Port, LED_L_45_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_90_R_GPIO_Port, LED_L_90_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_135_R_GPIO_Port, LED_L_135_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_180_R_GPIO_Port, LED_180_R_Pin, GPIO_PIN_RESET);
	}
	else if (deg < 23 + 45)
	{
		HAL_GPIO_WritePin(LED_0_R_GPIO_Port, LED_0_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_45_R_GPIO_Port, LED_R_45_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_90_R_GPIO_Port, LED_R_90_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_135_R_GPIO_Port, LED_R_135_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_45_R_GPIO_Port, LED_L_45_R_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(LED_L_90_R_GPIO_Port, LED_L_90_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_135_R_GPIO_Port, LED_L_135_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_180_R_GPIO_Port, LED_180_R_Pin, GPIO_PIN_RESET);
	}
	else if (deg < 23 + 45 * 2)
	{
		HAL_GPIO_WritePin(LED_0_R_GPIO_Port, LED_0_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_45_R_GPIO_Port, LED_R_45_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_90_R_GPIO_Port, LED_R_90_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_135_R_GPIO_Port, LED_R_135_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_45_R_GPIO_Port, LED_L_45_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_90_R_GPIO_Port, LED_L_90_R_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(LED_L_135_R_GPIO_Port, LED_L_135_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_180_R_GPIO_Port, LED_180_R_Pin, GPIO_PIN_RESET);
	}
	else if (deg < 23 + 45 * 3)
	{
		HAL_GPIO_WritePin(LED_0_R_GPIO_Port, LED_0_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_45_R_GPIO_Port, LED_R_45_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_90_R_GPIO_Port, LED_R_90_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_135_R_GPIO_Port, LED_R_135_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_45_R_GPIO_Port, LED_L_45_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_90_R_GPIO_Port, LED_L_90_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_135_R_GPIO_Port, LED_L_135_R_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(LED_180_R_GPIO_Port, LED_180_R_Pin, GPIO_PIN_RESET);
	}
	else if (deg < 23 + 45 * 4)
	{
		HAL_GPIO_WritePin(LED_0_R_GPIO_Port, LED_0_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_45_R_GPIO_Port, LED_R_45_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_90_R_GPIO_Port, LED_R_90_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_135_R_GPIO_Port, LED_R_135_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_45_R_GPIO_Port, LED_L_45_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_90_R_GPIO_Port, LED_L_90_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_135_R_GPIO_Port, LED_L_135_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_180_R_GPIO_Port, LED_180_R_Pin, GPIO_PIN_SET);
	}
	else if (deg < 23 + 45 * 5)
	{
		HAL_GPIO_WritePin(LED_0_R_GPIO_Port, LED_0_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_45_R_GPIO_Port, LED_R_45_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_90_R_GPIO_Port, LED_R_90_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_135_R_GPIO_Port, LED_R_135_R_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(LED_L_45_R_GPIO_Port, LED_L_45_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_90_R_GPIO_Port, LED_L_90_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_135_R_GPIO_Port, LED_L_135_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_180_R_GPIO_Port, LED_180_R_Pin, GPIO_PIN_RESET);
	}
	else if (deg < 23 + 45 * 6)
	{
		HAL_GPIO_WritePin(LED_0_R_GPIO_Port, LED_0_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_45_R_GPIO_Port, LED_R_45_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_90_R_GPIO_Port, LED_R_90_R_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(LED_R_135_R_GPIO_Port, LED_R_135_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_45_R_GPIO_Port, LED_L_45_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_90_R_GPIO_Port, LED_L_90_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_135_R_GPIO_Port, LED_L_135_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_180_R_GPIO_Port, LED_180_R_Pin, GPIO_PIN_RESET);
	}
	else if (deg < 23 + 45 * 7)
	{
		HAL_GPIO_WritePin(LED_0_R_GPIO_Port, LED_0_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_45_R_GPIO_Port, LED_R_45_R_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(LED_R_90_R_GPIO_Port, LED_R_90_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_135_R_GPIO_Port, LED_R_135_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_45_R_GPIO_Port, LED_L_45_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_90_R_GPIO_Port, LED_L_90_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_135_R_GPIO_Port, LED_L_135_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_180_R_GPIO_Port, LED_180_R_Pin, GPIO_PIN_RESET);
	}
	else if(deg < 360)
	{
		HAL_GPIO_WritePin(LED_0_R_GPIO_Port, LED_0_R_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(LED_R_45_R_GPIO_Port, LED_R_45_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_90_R_GPIO_Port, LED_R_90_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_R_135_R_GPIO_Port, LED_R_135_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_45_R_GPIO_Port, LED_L_45_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_90_R_GPIO_Port, LED_L_90_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_L_135_R_GPIO_Port, LED_L_135_R_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(LED_180_R_GPIO_Port, LED_180_R_Pin, GPIO_PIN_RESET);
	}
}
